---
- name: Delete deployments
  kubernetes.core.helm:
    name: "{{ deploy.name }}"
    chart_ref: apps-comparison-repo/{{ deploy.name }}
    namespace: "{{ namespace }}"
    update_repo_cache: yes
    kubeconfig: "{{ kubeconfig }}"
    state: absent
  with_items: "{{ reset.deployments }}"
  loop_control:
    loop_var: deploy