---
- name: Ensure apps-comparison-repo repo exists
  kubernetes.core.helm_repository:
    name: apps-comparison-repo
    repo_url: https://filbary.github.io/apps-comparison

- name: Ensure locust is deployed
  kubernetes.core.helm:
    name: locust
    chart_ref: apps-comparison-repo/locust
    namespace: "{{ namespace }}"
    update_repo_cache: yes
    kubeconfig: "{{ kubeconfig }}"
    state: present
    history_max: 3
    wait: false
    values:
      fullnameOverride: locust