replicaCount: 1

image:
  repository: filbary/locust
  pullPolicy: Always
  tag: "latest"

config: |
  locustfile = ./locustfiles
  class-picker = true

webapp:
  host: http://webapp:8080
  file: "./locustfiles/webapp.py"
  users: 70000
  spawnRate: 500
  runTime: 300
  csvFilename: "/statistics/"

serving:
  host: http://serving:8501
  file: "./locustfiles/serving.py"
  users: 70000
  spawnRate: 500
  runTime: 300
  csvFilename: "/statistics/"

imagePullSecrets: []
nameOverride: "locust"
fullnameOverride: "locust"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8089
  nodePort: 31700

resources: {}

volumes:
- name: config
  configMap:
    name: locust

volumeMounts:
- name: config
  mountPath: "/etc/mylocust"
  readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
